// Keep the existing business rules identical in the browser and on the server.
const fs = require('node:fs');
const html = fs.readFileSync('index.html', 'utf8');
const start = html.indexOf('function y(){let e=Promise.resolve()');
const end = html.indexOf('var Ee=`fieldbase-standalone-v1`', start);
if (start < 0 || end < 0) throw new Error('Business rules bundle boundaries changed');
fs.writeFileSync('lib/domain.cjs', '// Generated by scripts/extract-domain.cjs from index.html.\n' + html.slice(start, end) + '\nmodule.exports = { createState: de, applyAction: ge, normalize: ye, expected: x, employeeFor: K };\n');
